### ISSUE TITLE
Make tasks stuck with sbt 1.0

### ISSUE THREAD

**Issue by sean-liang** [typesafehub/sbteclipse#346] opened 2017-08-27 13:57 UTC
When sbteclipse plugin is installed, tasks like compile, console will stuck in sbt 1.0.

Environments:
Mac OS 10.12.6
Java 1.8.0_101
scala 2.12.3
sbt 1.0

build.sbt:
```
organization := "sbteclipse-test"

scalaVersion := "2.12.3"

version := "0.0.1-SNAPSHOT"

EclipseKeys.withSource := true
```

project/plugins.sbt
```
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "5.2.1")
```

project/build.properties
```
sbt.version=1.0.0
```

**Comment by wks** [comment] 2017-09-04 16:35
I can confirm this bug.  In my project, `sbt` stuck after `compile`, but the problem disappears if I removed `project/*.sbt` which contains the `addSbtPlugin` for `sbteclipse-plugin`.

**Comment by dmassart** [comment] 2017-09-04 17:27
I experience the problem too.  It disappears when downgrading to sbt.version=0.13.15 in project/build.properties

**Comment by benmccann** [comment] 2017-09-05 00:42
@godenji any ideas on this one?

**Comment by godenji** [comment] 2017-09-05 01:58
> any ideas on this one?

Not yet, just tried sample project on 1.0.0 and 1.0.1 and it hung as advertised. `inspect compile` differs between 1.0 and 0.13; not sure what's causing the hang, `debug` log reveals nothing obvious.

**Comment by godenji** [comment] 2017-09-05 13:13
It's the [Play Java hack](https://github.com/typesafehub/sbteclipse/blob/master/src/main/scala-sbt-1.0/com/typesafe/sbteclipse/core/EclipsePlugin.scala#L105), removing that from 1.0 source fixes the issue.

Will try to sort out hanging console while preserving this "feature", but at least we know where the problem is now.

**Comment by godenji** [comment] 2017-09-05 13:57
@benmccann fixed in #347

**Comment by benmccann** [comment] 2017-09-05 16:04
Thanks @godenji !!

I've released 5.2.2 with your fix

**Closed by benmccann** 2017-09-05 16:04 UTC

**Comment by godenji** [comment] 2017-09-05 16:33
@benmccann awesome, just pulled in 5.2.2 to test project, hanging console gone.

Now wait for sbt 1.0 support to land in Play -- hopefully soon, 0.13 is horrendous on many levels.

**Comment by benmccann** [comment] 2017-09-05 16:40
Is sbt 1.0 much better? I'm not really familiar with what changed

**Comment by godenji** [comment] 2017-09-05 16:44
Highlights for me are Scala 2.12 support in the build, and improved incremental compilation (which is an absolute productivity killer in 0.13 with large multi-subproject builds).

This is only important for Scala users of course, Java devs are largely insulated from the pain that sbt inflicts on its users.
