### ISSUE TITLE
compiled twirl as managed src?

### ISSUE THREAD

**Issue by mizerlou** [typesafehub/sbteclipse#229] opened 2014-11-07 21:24 UTC
all of my template references are flagged as errors in eclipse.  specifically, it'd say that the template was not in the html package.

i added this to my .classpath:
  &lt;classpathentry path="target/scala-2.11/twirl/main" kind="src"></classpathentry>
and that fixed up my problems quite nicely.

it *seems* like sbteclipse should be adding that by default.

**Comment by benmccann** [comment] 2015-03-12 10:54
I'm guessing you're using Play Scala?

**Comment by cweinreben** [comment] 2015-03-18 12:11
I have the same issue. I'm using Play Scala. 
sbt version 0.13.6
activator version 1.3.2
Eclipse version 4.4.2
Scala IDE version  4.0.0.v-2_11-201503031937-b2bbad6
Scala Play Plugin version  0.4.6.v-2_11-201503032139-4d44f99

Also have to add <classpathentry kind="src" path="target/scala-2.11/twirl/main"/> to the classpath manually.

**Comment by benmccann** [comment] 2015-03-18 15:34
@cweinreben it's the versions of Play and sbteclipse that you're using that really matter and you left those out :-)

We've checked in some workarounds to Play that will be in the next versions of Play released. I'll submit a real fix for this here as soon as my pending my PRs which the fix would depend on are checked in.

**Comment by cweinreben** [comment] 2015-03-18 16:20
Hi @benmccann , thank you for helping.
Regarding the missing versions - sorry we just started to Play :-)
Here they are:
Play version 2.3.8  
sbteclipse version 
Scala version 2.11.6
sbteclipse-plugin;3.0.0
sbteclipse-core;3.0.0

**Comment by benmccann** [comment] 2015-04-03 07:48
This is fixed in 4.0.0, which should be released soon

**Comment by Ciantic** [comment] 2015-06-19 14:42
Soon can't come soon enough. I tried and got hit by this with RC2, maybe release another RC?

**Comment by benmccann** [comment] 2015-06-19 14:54
This should definitely work correctly in RC2. Are you killing your sbt console and then rerunning the `eclipse` command? Do you have `EclipseKeys.createSrc` set in any way?

**Comment by Ciantic** [comment] 2015-06-19 15:00
@benmccann yes I have killed. I also just installed SBT and Scala IDE. If it was fixed shouldn't this work out of the box by running "eclipse"? What is the purpose of creating broken Eclipse project.

I found this line by googling:
`EclipseKeys.createSrc := EclipseCreateSrc.All`

Added to build.sbt

Ran eclipse, ran eclipse with-source, closed project re-opened. Not working.

**Comment by Ciantic** [comment] 2015-06-19 15:09
There is something funny going on perhaps.

The build.sbt says: `scalaVersion := "2.11.6"`

but `activator about` says `[info] sbt, sbt plugins, and build definitions are using Scala 2.10.4`

I downloaded latest SBT and Activator ~2 hours ago, and these are not compatible? I need to figure out how to get a newer scala or sbt, or something.

**Comment by benmccann** [comment] 2015-06-19 15:09
You need to run the `eclipse` command and refresh your project in the Eclipse program.

`EclipseKeys.createSrc := EclipseCreateSrc.All` is deprecated in 4.0 and now does the same thing as `EclipseKeys.createSrc := EclipseCreateSrc.Default` because `Default` should behave correctly now.

Can you post your .classpath file here? Also, are you using any framework like Play or writing your own project?

**Comment by Ciantic** [comment] 2015-06-19 15:11
@benmccann I've refreshed, and also closed and re-opened. It doesn't help. I changed the line to `EclipseKeys.createSrc := EclipseCreateSrc.Default` it didn't help. Perhaps I need to delete sbt, and .sbt and find a new version or something.

**Comment by benmccann** [comment] 2015-06-19 15:13
I think that your project and your build use different versions of scala. I don't think there's anything wrong with that.

Can you post your .classpath file here? Also, are you using any framework like Play or writing your own project?

**Comment by Ciantic** [comment] 2015-06-19 15:15
Yes this is vanilla Play project, using:

`activator new name play-scala`

```
<classpath>
  <classpathentry kind="src" path="app"/>
  <classpathentry kind="src" path="conf"/>
  <classpathentry excluding="resources\" kind="src" path="test"/>
  <classpathentry kind="con" path="org.scala-ide.sdt.launching.SCALA_CONTAINER"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.typesafe.play\twirl-api_2.11\jars\twirl-api_2.11-1.1.1.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.apache.commons\commons-lang3\jars\commons-lang3-3.4.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.typesafe.play\play-server_2.11\jars\play-server_2.11-2.4.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.typesafe.play\play_2.11\jars\play_2.11-2.4.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.typesafe.play\build-link\jars\build-link-2.4.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.typesafe.play\play-exceptions\jars\play-exceptions-2.4.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.javassist\javassist\bundles\javassist-3.19.0-GA.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.typesafe.play\play-iteratees_2.11\jars\play-iteratees_2.11-2.4.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.scala-stm\scala-stm_2.11\jars\scala-stm_2.11-0.7.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.typesafe\config\bundles\config-1.3.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.typesafe.play\play-json_2.11\jars\play-json_2.11-2.4.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.typesafe.play\play-functional_2.11\jars\play-functional_2.11-2.4.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.typesafe.play\play-datacommons_2.11\jars\play-datacommons_2.11-2.4.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\joda-time\joda-time\jars\joda-time-2.7.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.joda\joda-convert\jars\joda-convert-1.7.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.fasterxml.jackson.core\jackson-core\bundles\jackson-core-2.5.3.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.fasterxml.jackson.core\jackson-annotations\bundles\jackson-annotations-2.5.3.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.fasterxml.jackson.core\jackson-databind\bundles\jackson-databind-2.5.3.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.fasterxml.jackson.datatype\jackson-datatype-jdk8\bundles\jackson-datatype-jdk8-2.5.3.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.fasterxml.jackson.datatype\jackson-datatype-jsr310\bundles\jackson-datatype-jsr310-2.5.3.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.typesafe.play\play-netty-utils\jars\play-netty-utils-2.4.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.slf4j\slf4j-api\jars\slf4j-api-1.7.12.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.slf4j\jul-to-slf4j\jars\jul-to-slf4j-1.7.12.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.slf4j\jcl-over-slf4j\jars\jcl-over-slf4j-1.7.12.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\ch.qos.logback\logback-core\jars\logback-core-1.1.3.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\ch.qos.logback\logback-classic\jars\logback-classic-1.1.3.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.typesafe.akka\akka-actor_2.11\jars\akka-actor_2.11-2.3.11.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.typesafe.akka\akka-slf4j_2.11\jars\akka-slf4j_2.11-2.3.11.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\commons-codec\commons-codec\jars\commons-codec-1.10.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\xerces\xercesImpl\jars\xercesImpl-2.11.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\xml-apis\xml-apis\jars\xml-apis-1.4.01.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\javax.transaction\jta\jars\jta-1.1.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.google.inject\guice\jars\guice-4.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\javax.inject\javax.inject\jars\javax.inject-1.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\aopalliance\aopalliance\jars\aopalliance-1.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.google.inject.extensions\guice-assistedinject\jars\guice-assistedinject-4.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.typesafe.play\play-netty-server_2.11\jars\play-netty-server_2.11-2.4.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\io.netty\netty\bundles\netty-3.10.3.Final.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.typesafe.netty\netty-http-pipelining\jars\netty-http-pipelining-1.1.4.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.typesafe.play\play-jdbc_2.11\jars\play-jdbc_2.11-2.4.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.typesafe.play\play-jdbc-api_2.11\jars\play-jdbc-api_2.11-2.4.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.jolbox\bonecp\bundles\bonecp-0.8.0.RELEASE.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.zaxxer\HikariCP\bundles\HikariCP-2.3.7.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.h2database\h2\jars\h2-1.4.187.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\tyrex\tyrex\jars\tyrex-1.0.1.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.typesafe.play\play-cache_2.11\jars\play-cache_2.11-2.4.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\net.sf.ehcache\ehcache-core\jars\ehcache-core-2.6.11.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.typesafe.play\play-ws_2.11\jars\play-ws_2.11-2.4.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.google.guava\guava\bundles\guava-18.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.ning\async-http-client\jars\async-http-client-1.9.21.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\oauth.signpost\signpost-core\jars\signpost-core-1.2.1.2.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\oauth.signpost\signpost-commonshttp4\jars\signpost-commonshttp4-1.2.1.2.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.typesafe.play\play-test_2.11\jars\play-test_2.11-2.4.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\junit\junit\jars\junit-4.12.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.hamcrest\hamcrest-core\jars\hamcrest-core-1.3.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.novocode\junit-interface\jars\junit-interface-0.11.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.scala-sbt\test-interface\jars\test-interface-1.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.google.code.findbugs\jsr305\jars\jsr305-2.0.3.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.fluentlenium\fluentlenium-core\jars\fluentlenium-core-0.10.3.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.seleniumhq.selenium\selenium-java\jars\selenium-java-2.44.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.seleniumhq.selenium\selenium-chrome-driver\jars\selenium-chrome-driver-2.44.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.seleniumhq.selenium\selenium-remote-driver\jars\selenium-remote-driver-2.44.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\cglib\cglib-nodep\jars\cglib-nodep-2.1_3.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.google.code.gson\gson\jars\gson-2.3.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.seleniumhq.selenium\selenium-api\jars\selenium-api-2.44.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.apache.httpcomponents\httpclient\jars\httpclient-4.3.4.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.apache.httpcomponents\httpcore\jars\httpcore-4.3.2.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\commons-logging\commons-logging\jars\commons-logging-1.1.3.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.apache.commons\commons-exec\jars\commons-exec-1.1.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\net.java.dev.jna\jna\jars\jna-3.4.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\net.java.dev.jna\platform\jars\platform-3.4.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.seleniumhq.selenium\selenium-htmlunit-driver\jars\selenium-htmlunit-driver-2.44.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\net.sourceforge.htmlunit\htmlunit\jars\htmlunit-2.15.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\xalan\xalan\jars\xalan-2.7.1.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\xalan\serializer\jars\serializer-2.7.1.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\commons-collections\commons-collections\jars\commons-collections-3.2.1.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.apache.httpcomponents\httpmime\jars\httpmime-4.3.3.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\net.sourceforge.htmlunit\htmlunit-core-js\jars\htmlunit-core-js-2.15.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\net.sourceforge.nekohtml\nekohtml\jars\nekohtml-1.9.21.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\net.sourceforge.cssparser\cssparser\jars\cssparser-0.9.14.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.w3c.css\sac\jars\sac-1.3.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\commons-io\commons-io\jars\commons-io-2.4.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.eclipse.jetty\jetty-websocket\jars\jetty-websocket-8.1.15.v20140411.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.eclipse.jetty\jetty-util\jars\jetty-util-8.1.15.v20140411.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.eclipse.jetty\jetty-io\jars\jetty-io-8.1.15.v20140411.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.eclipse.jetty\jetty-http\jars\jetty-http-8.1.15.v20140411.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.seleniumhq.selenium\selenium-firefox-driver\jars\selenium-firefox-driver-2.44.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.seleniumhq.selenium\selenium-ie-driver\jars\selenium-ie-driver-2.44.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.seleniumhq.selenium\selenium-safari-driver\jars\selenium-safari-driver-2.44.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.webbitserver\webbit\jars\webbit-0.4.14.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.seleniumhq.selenium\selenium-support\jars\selenium-support-2.44.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\com.typesafe.play\play-specs2_2.11\jars\play-specs2_2.11-2.4.0.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.specs2\specs2-core_2.11\jars\specs2-core_2.11-3.6.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.specs2\specs2-matcher_2.11\jars\specs2-matcher_2.11-3.6.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.specs2\specs2-common_2.11\jars\specs2-common_2.11-3.6.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.scalaz\scalaz-core_2.11\bundles\scalaz-core_2.11-7.1.1.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.scala-lang.modules\scala-parser-combinators_2.11\bundles\scala-parser-combinators_2.11-1.0.2.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.scala-lang.modules\scala-xml_2.11\bundles\scala-xml_2.11-1.0.2.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.scalaz\scalaz-concurrent_2.11\bundles\scalaz-concurrent_2.11-7.1.1.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.scalaz\scalaz-effect_2.11\bundles\scalaz-effect_2.11-7.1.1.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.scalaz.stream\scalaz-stream_2.11\bundles\scalaz-stream_2.11-0.7a.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.scodec\scodec-bits_2.11\bundles\scodec-bits_2.11-1.0.6.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.specs2\specs2-junit_2.11\jars\specs2-junit_2.11-3.6.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.specs2\specs2-mock_2.11\jars\specs2-mock_2.11-3.6.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.mockito\mockito-core\jars\mockito-core-1.9.5.jar"/>
  <classpathentry kind="lib" path="C:\Users\Jarppa\.ivy2\cache\org.objenesis\objenesis\jars\objenesis-1.0.jar"/>
  <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
  <classpathentry kind="output" path="bin"/>
</classpath>
```

**Comment by Ciantic** [comment] 2015-06-19 15:21
interesting, some reason my paste got shortened "..." it was full just a minute ago.

**Comment by Ciantic** [comment] 2015-06-19 15:31
Btw, part of the problem is Play Framework docs: https://www.playframework.com/documentation/2.4.x/IDE

It says `addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "4.0.0")` which is kind of lie, this version does not exist yet, it was the first hurdle I had to find when trying Play.

**Comment by Ciantic** [comment] 2015-06-19 15:51
@benmccann do you know can I hack this to work? Editing .classpath myself? I'd like to try Play again.

**Comment by benmccann** [comment] 2015-06-19 15:52
@Ciantic I think I figured this out. Run `sbt compile` then `sbt eclipse` and it should add `target/scala-2.11/twirl/main` to your `.classpath` file so that things work for you. I can update the Play docs to mention this. If this works for you then we should release 4.0.0 so that the docs are also correct in that regard and don't require you to rely on an RC

**Closed by benmccann** 2015-06-19 15:52 UTC

**Comment by Ciantic** [comment] 2015-06-19 15:53
@benmccann yes! It works, thank you very much. I had not run `compile` before running eclipse.

**Comment by benmccann** [comment] 2015-06-19 16:02
Ok. I've sent a PR to update the docs to mention that: https://github.com/playframework/playframework/pull/4721
