### ISSUE TITLE
Plugin is not playing well with Scala IDE 4.6.1

### ISSUE THREAD

**Issue by ekrich** [typesafehub/sbteclipse#342] opened 2017-08-02 15:38 UTC
The plugin overwrites settings set in Eclipse and plugin does not add an entry for the Scala version in `.settings/org.scala-ide.sbt.core.prefs` as follows:
```
scala.compiler.installation=2.11
scala.compiler.sourceLevel=2.11
```
Note that the first entry can only be set to a number as follows if a `Fixed` Scala is set in the IDE versus a `Dynamic` as shown above.
```
scala.compiler.installation=-1182919327
```
I think if the `build.sbt` changed from `2.11` to `2.12` for example both would need to change.

See - https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1002901-scala-version-changes-when-using-scala-ide-and-sbteclipse/details#

**Comment by cs4inctec** [comment] 2017-09-21 12:06
seems this issue is related to #338

**Comment by benmccann** [comment] 2017-11-17 00:13
Yes, closing as a duplicate of https://github.com/typesafehub/sbteclipse/issues/338. Just FYI, I'm reviewing pull requests with fixes, but not writing any of mine own, so if you want to take a stab at it I'll try to be responsive in reviewing

**Closed by benmccann** 2017-11-17 00:13 UTC
